version: '3.9'

networks:
  mass-networks:
    external: true

volumes:
  zookeeper_mass:
    external: false
  kafka_mass:
    external: false

services:
  zookeeper_mass:
    platform: linux/amd64
    image: confluentinc/cp-zookeeper:5.3.1
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_mass:/data
    ports:
      - 2181:2181
    networks:
      - mass-networks


  kafka_mass:
    platform: linux/amd64
    image: confluentinc/cp-kafka:5.3.1
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_mass:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_mass:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSERTS_TOPICS_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_mass:/var/lib/kafka/data
    ports:
      - 9092:9092
    networks:
      - mass-networks
